



usr/lib/x86_64-linux-gnu/libopencv_cudaarithm.so
usr/lib/x86_64-linux-gnu/libopencv_cudaarithm.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudaarithm.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudabgsegm.so
usr/lib/x86_64-linux-gnu/libopencv_cudabgsegm.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudabgsegm.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudacodec.so
usr/lib/x86_64-linux-gnu/libopencv_cudacodec.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudacodec.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudafeatures2d.so
usr/lib/x86_64-linux-gnu/libopencv_cudafeatures2d.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudafeatures2d.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudafilters.so
usr/lib/x86_64-linux-gnu/libopencv_cudafilters.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudafilters.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudaimgproc.so
usr/lib/x86_64-linux-gnu/libopencv_cudaimgproc.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudaimgproc.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudalegacy.so
usr/lib/x86_64-linux-gnu/libopencv_cudalegacy.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudalegacy.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudaobjdetect.so
usr/lib/x86_64-linux-gnu/libopencv_cudaobjdetect.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudaobjdetect.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudaoptflow.so
usr/lib/x86_64-linux-gnu/libopencv_cudaoptflow.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudaoptflow.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudastereo.so
usr/lib/x86_64-linux-gnu/libopencv_cudastereo.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudastereo.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudawarping.so
usr/lib/x86_64-linux-gnu/libopencv_cudawarping.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudawarping.so.4.2.0
usr/lib/x86_64-linux-gnu/libopencv_cudev.so
usr/lib/x86_64-linux-gnu/libopencv_cudev.so.4.2
usr/lib/x86_64-linux-gnu/libopencv_cudev.so.4.2.0
